homework/week05/sparta/__init__.py
from flask import Flask

import config


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    from .views import main_views, memo_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(memo_views.bp)
    return app

homework/week05/sparta/views/main_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('memo._land'))

homework/week05/sparta/views/memo_views.py
from flask import Blueprint, render_template, request
from pymongo import MongoClient
import hashlib

bp = Blueprint('memo', __name__, url_prefix='/memo')


client = MongoClient('localhost', 27017)
db = client.assign05


@bp.route('/')
def _land():
    return render_template('memo/memo_landing.html')

@bp.route('/login', methods=['GET'])
def login():
    return render_template('memo/memo_login.html')

@bp.route('/signup', methods=['GET'])
def signup():
    return render_template('memo/memo_signup.html')

bp.route('/api/signup', methods=['POST'])
def api_signup():
    id = request.form['id_give']
    pw = request.form['pw_give']

    pw_hash = hashlib.sha256(pw.encode()).hexdigest()
    db.user.insert_one({'id':id, 'pw':pw_hash})

    return jsonify({'result' : 'success'})

homework/week05/sparta/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <title>Document</title>
</head>

<body>
    <!-- 기본 템플릿에 삽입할 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿에 삽입하 내용 End -->
</body>

</html>

homework/week05/sparta/templates/memo/memo_landing.html
{% extends 'base.html' %}
{% block content %}
<div class="wrap">
    <div id="user-info"></div>
    <div class="jumbotron">
        <h1 class="display-4">{{ test }} 메모장!</h1>
        <p class="lead">중요한 링크를 저장해두고, 나중에 볼 수 있는 공간입니다</p>
        <hr class="my-4">
        <p class="lead">
            <button onclick="openClose()" id="btn-post-box" type="button" class="btn btn-primary">포스팅 박스 열기
            </button>
        </p>
</div>
<script src="{{ url_for('static', filename='memo/memo_landing.js') }}"></script>
{% endblock %}

homework/week05/sparta/templates/memo/memo_login.html
{% extends 'base.html' %}
{% block content %}
<h1>로그인 페이지</h1>
<div>
    <div class="form-group">
        <label for="userid">ID</label>
        <input type="email" class="form-control" id="userid" aria-describedby="emailHelp" placeholder="My ID">
    </div>
    <div class="form-group">
        <label for="userpw">PW</label>
        <input type="password" class="form-control" id="userpw" placeholder="My Password">
    </div>
    <button class="btn btn-primary" onclick="login()">로그인</button>
    <a href="{{ url_for('memo.signup') }}">회원이 아니라면?</a>
</div>
<script src="{{ url_for('static', filename='memo/memo_login.js') }}"></script>
{% endblock content %}
    

homework/week05/sparta/templates/memo/memo_signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입 페이지</h1>
<div>
    <div class="form-group">
        <label for="userid">ID</label>
        <input type="text" class="form-control" id="userid" aria-describedby="emailHelp" placeholder="My ID">
    </div>
    <div class="form-group">
        <label for="userpw">PW</label>
        <input type="password" class="form-control" id="userpw" placeholder="My Password">
    </div>
    <button class="btn btn-primary" onclick="register()">회원가입</button>
</div>
<script src="{{ url_for('static', filename='memo/memo_signup.js') }}"></script>

{% endblock content %}