week05/sparta/views/memo_views.py
from flask import Blueprint, json, render_template, request, jsonify
from pymongo import MongoClient
import hashlib
import datetime
import jwt
from flask.cli import load_dotenv
import os
from bs4 import BeautifulSoup
import requests
bp = Blueprint('memo', __name__, url_prefix='/memo')

client = MongoClient('localhost', 27017)
db = client.week05

# .env 파일을 환경변수로 설정
load_dotenv()
# 환경변수 읽어오기
JWT_SECRET = os.environ['JWT_SECRET']
CLIENT_ID = os.environ['CLIENT_ID']
CALLBACK_URL = os.environ['CALLBACK_URL']
SERVICE_URL = os.environ['SERVICE_URL']


@bp.route('/',  methods=['GET'])
def memo_landing():
    # API 추가
    # 그냥 ['key']면 에러날 수 있으니까 get으로 가져옴(없을 경우 None)
    token = request.cookies.get('loginToken')

    if token:
        try:
            payload = jwt.decode(token, JWT_SECRET, algorithms=['HS256'])
            id = payload['id']
            memos = list(db.articles.find({'id': id}, {'_id': False}))
        except jwt.ExpiredSignatureError:
            memos = []
    else:
        memos = []

    return render_template('memo/memo_landing.html', test='테스트', memos=memos)


@bp.route('/login', methods=['GET'])
def memo_login():
    CLIENT_ID = os.environ['CLIENT_ID']
    CALLBACK_URL = os.environ['CALLBACK_URL']
    SERVICE_URL = os.environ['SERVICE_URL']
    return render_template('memo/memo_login.html', CLIENT_ID=CLIENT_ID, CALLBACK_URL=CALLBACK_URL, SERVICE_URL=SERVICE_URL)

@ bp.route('/api/login', methods=['POST'])
def api_login():
    id = request.form['id_give']
    pw = request.form['pw_give']

    # TODO id, pw 검증 후에 JWT 만들어서 리턴
    pw_hash = hashlib.sha256(pw.encode()).hexdigest()

    user = db.users.find_one({'id': id, 'pw': pw_hash}, {'_id': False})

    # 만약 가입했다면
    if user:
        # 로그인 성공 -> JWT 생성
        expiration_time = datetime.timedelta(hours=1)
        payload = {
            'id': id,
            # 발급시간으로부터 1시간동안 JWT 유효
            'exp': datetime.datetime.utcnow() + expiration_time
        }
        token = jwt.encode(payload, JWT_SECRET)
        print(token)
        return jsonify({'result': 'success', 'token': token})
    else:
        return jsonify({'result': 'fail', 'msg': '로그인 실패'})
    # 가입하지 않은 상태


@bp.route('/signup')
def memo_signup():
    return render_template('memo/memo_signup.html')


@bp.route('/api/signup', methods=['POST'])
def api_signup():
    id = request.form['id_give']
    pw = request.form['pw_give']

    # md5, sha1은 안됨. 우리나라에서 어떤 알고리즘 써야할지 정해주었음
    pw_hash = hashlib.sha256(pw.encode()).hexdigest()

    # 회원가입
    db.users.insert_one({'id': id, 'pw': pw_hash})
    return jsonify({'result': 'success'})


@bp.route('/user', methods=['POST'])
def user_info():
    token_receive = request.headers['authorization']
    token = token_receive.split()[1]
    print('token', token)
    try:
        payload = jwt.decode(token, JWT_SECRET, algorithms=['HS256'])
        print(payload)
        return jsonify({'result': 'success', 'id': payload['id']})
    except jwt.exceptions.ExpiredSignatureError:
        # 에러 대응
        return jsonify({'result': 'fail', 'msg': 'ExpiredSignature'})


@bp.route('/create/article', methods=['POST'])
def save_memo():
    url_receive = request.form['url_give']
    comment_receive = request.form['comment_give']

    token_receive = request.headers['authorization']
    token = token_receive.split()[1]
    try:
        # JWT 페이로드에서 id 확인
        payload = jwt.decode(token, JWT_SECRET, algorithms=['HS256'])
        id = payload['id']

        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
        response = requests.get(
            url_receive,
            headers=headers
        )
        soup = BeautifulSoup(response.text, 'html.parser')

        title = soup.select_one('meta[property="og:title"]')
        url = soup.select_one('meta[property="og:url"]')
        image = soup.select_one('meta[property="og:image"]')
        description = soup.select_one('meta[property="og:description"]')
        print(title['content'])
        print(url['content'])
        print(image['content'])
        print(description['content'])
        document = {
            'title': title['content'],
            'image': image['content'],
            'description': description['content'],
            'url': url['content'],
            'comment': comment_receive,
            'id': id,
        }
        db.articles.insert_one(document)
        return jsonify(
            {'result': 'success', 'msg': '저장했습니다.'}
        )
    except jwt.ExpiredSignatureError:
        return jsonify({'result': 'fail', 'msg': '로그인 시간이 만료되었습니다.'})


@bp.route('/naver', methods=['GET'])
def callback():
    CLIENT_ID = os.environ['CLIENT_ID']
    CALLBACK_URL = os.environ['CALLBACK_URL']
    SERVICE_URL = os.environ['SERVICE_URL']
    return render_template('memo/callback.html', CALLBACK_URL=CALLBACK_URL, CLIENT_ID=CLIENT_ID, SERVICE_URL=SERVICE_URL)

# 네이버 가입 API
@bp.route('/api/register/naver', methods=['POST'])
def api_register_naver():
    naver_id = request.form['naver_id_give']
    print(naver_id)

    # 아직 가입하지 않은 naver id 케이스에서는 가입까지 처리
    if not db.user.find_one({'id': naver_id}, {'_id': False}):
        db.user.insert_one({'id': naver_id, 'pw': ''})

    expiration_time = datetime.timedelta(hours=1)
    payload = {
        'id': naver_id,
        # JWT 유효 기간 - 이 시간 이후에는 JWT 인증이 불가능합니다.
        'exp': datetime.datetime.utcnow() + expiration_time,
    }
    token = jwt.encode(payload, JWT_SECRET)

    return jsonify({'result': 'success', 'token': token})

week05/sparta/templates/memo/callback.html
<!doctype html>
<html lang="ko">

<head>
    <script type="text/javascript" src="https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js" charset="utf-8">
    </script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- 쿠키 사용을 위한 Jquery-cookie 임포트 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
</head>

<body>
    <script type="text/javascript">
        var naver_id_login = new naver_id_login("{{ CLIENT_ID }}", "{{ CALLBACK_URL }}");
        // 접근 토큰 값 출력
        // alert(naver_id_login.oauthParams.access_token);
        // 네이버 사용자 프로필 조회
        naver_id_login.get_naver_userprofile("naverSignInCallback()");

        // 네이버 사용자 프로필 조회 이후 프로필 정보를 처리할 callback function
        function naverSignInCallback() {
            let naver_id = naver_id_login.getProfileData('id');
            // getProfileData 이용해 가져올 수 있는 값들
            // success: function (result) {
            //     inner_profileParams.age           = result.response.age;
            //     inner_profileParams.birthday      = result.response.birthday;
            //     inner_profileParams.email         = result.response.email;
            //     inner_profileParams.enc_id        = result.response.enc_id;
            //     inner_profileParams.gender        = result.response.gender;
            //     inner_profileParams.id            = result.response.id;
            //     inner_profileParams.nickname      = result.response.nickname;
            //     inner_profileParams.profile_image = result.response.profile_image;
            //     inner_profileParams.name          = result.response.name;
            //     eval(callback_func1);
            // }

            // 네아로 정보를 이용해 회원가입하고 JWT 쿠키에 저장
            $.ajax({
                type: "POST",
                url: "/memo/api/register/naver",
                data: {
                    'naver_id_give': naver_id
                },
                success: function (response) {
                    if (response['result'] == 'success') {
                        // 로그인이 정상적으로 되면, 토큰을 받아옵니다.
                        // 이 토큰을 mytoken이라는 키 값으로 쿠키에 저장합니다.
                        $.cookie('loginToken', response['token']);

                        alert('로그인 완료!')
                        window.location.href = '/memo'
                    } else {
                        // 로그인이 안되면 에러메시지를 띄웁니다.
                        alert(response['msg'])
                    }
                }
            })
            alert(naver_id_login.getProfileData('email'));
        }
    </script>
</body>

</html>

week05/sparta/templates/memo/memo_landing.html
<!Doctype html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <!-- 구글폰트 -->
    <link href="https://fonts.googleapis.com/css?family=Stylish&display=swap" rel="stylesheet">
    <title>스파르타코딩클럽 | 나홀로 메모장</title>
    <!-- style -->
    <style type="text/css">
        * {
            font-family: "Stylish", sans-serif;
        }

        .wrap {
            width: 900px;
            margin: auto;
        }

        .comment {
            color: blue;
            font-weight: bold;
        }

        #post-box {
            width: 500px;
            margin: 20px auto;
            padding: 50px;
            border: black solid;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <div class="wrap">
        <div id="user-info"></div>
        <div class="jumbotron">
            <h1 class="display-4">나홀로 링크 메모장!</h1>
            <p class="lead">중요한 링크를 저장해두고, 나중에 볼 수 있는 공간입니다</p>
            <hr class="my-4">
            <p class="lead">
                <button onclick="openClose()" id="btn-post-box" type="button" class="btn btn-primary">포스팅 박스 열기
                </button>
            </p>
        </div>
        <div id="post-box" class="form-post" style="display:none">
            <div>
                <div class="form-group">
                    <label for="post-url">아티클 URL</label>
                    <input id="post-url" class="form-control" placeholder="">
                </div>
                <div class="form-group">
                    <label for="post-comment">간단 코멘트</label>
                    <textarea id="post-comment" class="form-control" rows="2"></textarea>
                </div>
                <button type="button" class="btn btn-primary" onclick="postArticle()">기사저장</button>
            </div>
        </div>
        <div id="cards-box" class="card-columns">
            {% for memo in memos %}
            <div class="card">
                <img class="card-img-top" src="{{ memo['image'] }}" alt="Card image cap">
                <div class="card-body">
                    <a href="{{ memo['url'] }}" class="card-title">{{ memo['title'] }}</a>
                    <p class="card-text">{{ memo['description'] }}</p>
                    <p class="card-text comment">{{ memo['comment'] }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script src="../../static/memo/memo_landing.js"></script>
</body>

</html>

week05/sparta/templates/memo/memo_login.html
<!-- templates/login.html -->
<!doctype html>
<html lang="en">

<head>

    <!-- Webpage Title -->
    <title>Hello, world!</title>

    <!-- Required meta tags -->
    <link rel="shortcut icon" href="#">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script type="text/javascript" src="https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js" charset="utf-8">
    </script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- 쿠키 사용을 위한 Jquery-cookie 임포트 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>

</head>

<body>
    <h1>로그인 페이지</h1>
    <div>
        <div class="form-group">
            <label for="userid">ID</label>
            <input type="email" class="form-control" id="userid" aria-describedby="emailHelp" placeholder="My ID">
        </div>
        <div class="form-group">
            <label for="userpw">PW</label>
            <input type="password" class="form-control" id="userpw" placeholder="My Password">
        </div>
        <button class="btn btn-primary" onclick="login()">로그인</button>
        <a href="{{ url_for('memo.memo_signup') }}">회원이 아니라면?</a>
        <!-- 네아로 개발도구(head 태그 안) -->

        <!-- 네아로 버튼(body 태그 안) -->
        <!-- 네이버아이디로로그인 버튼 노출 영역 -->

        <div id="naver_id_login"></div>
        <!-- //네이버아이디로로그인 버튼 노출 영역 -->
        <script>
            var naver_id_login = new naver_id_login("{{ CLIENT_ID }}", "{{ CALLBACK_URL }}");
            var state = naver_id_login.getUniqState();
            naver_id_login.setButton("white", 2, 40);
            naver_id_login.setDomain("{{ SERVICE_URL }}");
            naver_id_login.setState(state);
            naver_id_login.init_naver_id_login();
        </script>

    </div>
</body>

</html>

week05/sparta/templates/memo/memo_signup.html
<!-- templates/register.html -->
<!doctype html>
<html lang="en">
<head>

    <!-- Webpage Title -->
    <title>Hello, world!</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <script>
        // 간단한 회원가입 함수입니다.
        // 아이디, 비밀번호, 닉네임을 받아 DB에 저장합니다.
        function signup() {
            $.ajax({
                type: "POST",
                url: "/memo/api/signup",
                data: {id_give: $('#userid').val(), pw_give: $('#userpw').val()},
                success: function (response) {
                    if (response['result'] == 'success') {
                        alert('회원가입이 완료되었습니다.')
                        window.location.href = '/memo/login'
                    } else {
                        alert(response['msg'])
                    }
                }
            })
        }

    </script>
</head>
<body>
<h1>회원가입 페이지</h1>
<div>
    <div class="form-group">
        <label for="userid">ID</label>
        <input type="text" class="form-control" id="userid" aria-describedby="emailHelp" placeholder="My ID">
    </div>
    <div class="form-group">
        <label for="userpw">PW</label>
        <input type="password" class="form-control" id="userpw" placeholder="My Password">
    </div>
    <button class="btn btn-primary" onclick="signup()">회원가입</button>
</div>
</body>
</html>